### ISSUE TITLE
Feature request: list command with parameters to filter / sort passwords

### ISSUE THREAD

**Issue by kizm0** [Nitrokey/trussed-secrets-app#107]
with the list command i am able to list all stored passwords/otps on the nk3-device, for more convenience it would be helpful that the list command has the option --filter [name|type] 'regex or string' and --sort-by [name|id|type|...]  
pretty optional cause the same results can be achieved with linux commands sort and grep, but it would me more easy for users, maybe useful in nitrokey-app2 (ui) to not retrieve all secrets of device (if filter/sort is implemented there)

**Comment by robin-nitrokey** [comment]
This repository contains the firmware implementation of the secrets app.  From my understanding, you just want to have this feature in the client (pynitrokey/nitrokey-app2) and not necessarily in the firmware, right?

**Comment by robin-nitrokey** [comment]
Thanks for the clarification.  I’ve created separate tickets for pynitrokey and nitrokey-app2 for this feature request:
- https://github.com/Nitrokey/pynitrokey/issues/498
- https://github.com/Nitrokey/nitrokey-app2/issues/205
