### ISSUE TITLE
maximum number of secrets (50?)

### ISSUE THREAD

**Issue by kizm0** [Nitrokey/trussed-secrets-app#119]
Hello,

i do have a Nitrokey 3 which stores 50 passwords in the secret app. By adding the 51th i get the error AddCredentialJobSecretsAppException(NotEnoughMemory). I was not able to find any hardcoded limitation of secrets. Is there a limitation of secrets (number/total bytes)?

Thank you!

**Comment by robin-nitrokey** [comment]
Indeed there currently is a hard limit of 50 credentials.  The reason for this is that listing all credentials can get pretty slow if there are many (several hundred).  We therefore chose a rather conservative limit for the first release.  We definitely plan to significantly increase the limit once we have improved the iteration speed and implemented faster alternatives.  I’ve created a tracking issue for that:  https://github.com/Nitrokey/trussed-secrets-app/issues/120

We already did some of the work required for this, but there are still some components missing.  As a first step, we could maybe add a configuration option to increase the limit for users that are willing to pay the performance penalty.
