### ISSUE TITLE
Add Password Safe

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/trussed-secrets-app#60]
Introduce Password Safe feature - store login, password, and any additional metadata (client encoded)

**Comment by kizm0** [comment]
how can this feature (password safe) be used with nitrokey3 firmware v1.5? secrets app only allows kind TOTP, HOTP, HOTP_REVERSE to register?

**Comment by szszszsz** [comment]
Hi!
A new pynitrokey version is required to use it, which should be released tomorrow.
The relevant PR is here: https://github.com/Nitrokey/pynitrokey/pull/393

**Comment by kizm0** [comment]
i just tried - works like a charm :) thanks for your work - keep up
