### ISSUE TITLE
NK3AM fails to register a Credential in the clean state

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/trussed-secrets-app#88]
NK3AM seem to fail to register a Credential in the clean state during a Heads setup operation.
The subsequent attempt works.

From the discussion:
> ok seems like if you fail to touch it during the hotp check (a window around 1s) then it is not recognized after that and the OEM reset failed - I suspect this is true for all the hotp checks

> ah interesting - it does just happen for the first oem reset - if you do a second one after that it does not occur

> this problem only happens, if you do a `hotp_verification info` before a `gpg --card-edit` on a fresh key
> after the first time `gpg --card-edit` (without doing anything) it works without the touch 

> also hotp_verification info does not show the firmware version and the serial;
> only after this gpg --card-edit

Touch implementation for the NK3 AM:
- https://github.com/Nitrokey/nitrokey-3-firmware/blob/6fe0e242b92a4d58806360a10fe1dda792e7a174/runners/embedded/src/soc_nrf52840/trussed_ui.rs#L96

CCID interface implementation in Nitrokey HOTP Verification Tool:
- https://github.com/Nitrokey/nitrokey-hotp-verification/blob/master/src/operations_ccid.c

Secrets App versions on NK3 firmware:
- v1.4 -> 0.10
- v1.5 -> 0.11

![image](https://github.com/Nitrokey/trussed-secrets-app/assets/17005426/7253f765-08b4-4357-baac-38812d2509ea)

**Comment by nestire** [comment]
Reproduce with:
a fresh nk3am from produktion, execute 
`hotp_verification info`
it will ask for a touch, after that it will be not responsive anymore even with succesfull touch (1.5) on 1.4 it was only unresponsive if the touch was not there.  to be responsive again it needs a power cricle

**Comment by sosthene-nitrokey** [comment]
I don't think https://github.com/trussed-dev/usbd-ccid/pull/13 would fix the issue. All it does is reset the state when there is an unexpected input rather than panicking. It still would not properly deal with the badly formatted input.

**Comment by szszszsz** [comment]
Yes - I was referring to the crash inducing behavior (which is a direct cause of the problem).

**Comment by szszszsz** [comment]
The following is not crashing the firmware, but is one of the causes of the further malfunction:
```
_msg = (&str) "Reset\n"
_msg = (&str) "Trussed backend error: FilesystemReadFailure (line 1233)\n"
_msg = (&str) "OTP command execution error: UnspecifiedNonpersistentExecutionError\n"
```

which connects to:
https://github.com/Nitrokey/trussed-secrets-app/blob/a95b8ed534c3c7bbaa9a5a4c07ccbb83fcc66492/src/authenticator.rs#L1226-L1236

**Comment by sosthene-nitrokey** [comment]
I took a look at it. The error is simply that the timeout is too short. For some reason the device does not respond within 1s, which leads to the `libusb_bulk_transfer` call in `ccid_receive` function to fail. This leaves the device in a `Processing` state without being cleaned up, so the next commands error.

Increasing the timeout fixes the issue.
This also explains why some circumstances are faster than others, I guess that the first calls after factory reset require re-building a default state, which explains why the timeout is only reached in that case and not when the device is operating properly.

**Comment by szszszsz** [comment]
1. Thanks for checking. I've noticed that as well, and increased the timeout to 3 seconds, making it work reliably again. I do not understand though, why the first call in the session always timeouts.
2. I am perplexed by the cause of the panic. Should not the outgoing buffer be cleared, if the message was not received, and another request comes?
3. What about https://github.com/Nitrokey/trussed-secrets-app/issues/88#issuecomment-1594567227 @sosthene-nitrokey ?

**Comment by sosthene-nitrokey** [comment]
> I do not understand though, why the first call in the session always timeouts.

To copy what was said in private: my initial theory was that it's rebuilding/storing the state.

> I am perplexed by the cause of the panic. Should not the outgoing buffer be cleared, if the message was not received, and another request comes?

Yes see https://github.com/trussed-dev/usbd-ccid/pull/13

**Comment by sosthene-nitrokey** [comment]
> The following is not crashing the firmware, but is one of the causes of the further malfunction:
> 
> ```
> _msg = (&str) "Reset\n"
> _msg = (&str) "Trussed backend error: FilesystemReadFailure (line 1233)\n"
> _msg = (&str) "OTP command execution error: UnspecifiedNonpersistentExecutionError\n"
> ```
> 
> which connects to:
> 
> https://github.com/Nitrokey/trussed-secrets-app/blob/a95b8ed534c3c7bbaa9a5a4c07ccbb83fcc66492/src/authenticator.rs#L1226-L1236
> 
> cc @sosthene-nitrokey Is this worth investigating? Can we recover from this?

Yes, it looks concerning. Not sure what can cause read failures. It feels like something that should never happen

**Comment by sosthene-nitrokey** [comment]
### Re: Filesystem corruption

Maybe the error is not actual filesystem corruption but rather an incomplete state? A non-existent file being read would lead to this error.

**Comment by szszszsz** [comment]
The file was claimed to be existing actually:
trussed-auth-53c577462e9e97b3/d704b04/src/backend/data.rs

```rust
pub(crate) fn get_app_salt<S: Filestore, R: CryptoRng + RngCore>(
    fs: &mut S,
    rng: &mut R,
    location: Location,
) -> Result<Salt, Error> {
    if !fs.exists(&app_salt_path(), location) {
        create_app_salt(fs, rng, location)
    } else {
        load_app_salt(fs, location)
    }
}
```

**Comment by szszszsz** [comment]
Just FYI, timeout value increase is not the sole fix for this one I am afraid @sosthene-nitrokey :
```
~/w/n/cmake-build-debug (master|✚1) $ ninja; ./hotp_verification set GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ "" 2
>&1 | grep Time
ninja: no work to do.
*** Time for ccid_send: 0
*** Time for ccid_receive: 4000
*** Time for ccid_send: 0
*** Time for ccid_receive: 25
*** Time for ccid_send: 0
*** Time for ccid_receive: 2
*** Time for ccid_send: 0
*** Time for ccid_receive: 336
~/w/n/cmake-build-debug (master|✚1) $ ninja; ./hotp_verification set GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ "" 2
>&1 | grep Time
ninja: no work to do.
*** Time for ccid_send: 0
*** Time for ccid_receive: 4000
*** Time for ccid_send: 0
*** Time for ccid_receive: 4000
*** Time for ccid_send: 1
*** Time for ccid_receive: 360
~/w/n/cmake-build-debug (master|✚1) $

```

**Comment by sosthene-nitrokey** [comment]
I do not understand what I am seeing.
Some operations take more than 4 seconds?

**Comment by szszszsz** [comment]
Nope. Some operations are timing out regardless of the set timeout value. 4 seconds is a lot. 10 seconds even more.

**Comment by szszszsz** [comment]
In the further tests it turned out, that setting timeout to 200ms results in the exact same behavior, that is the very first request is not responded to (timed out), but further requests are working as expected.
Further work: check usb-ccid crate in the NK3 firmware.

**Comment by sosthene-nitrokey** [comment]
Does it reproduce with the usbip runner?

**Comment by szszszsz** [comment]
I do not support CCID in my USB/IP setup currently. Do you have any working where I could draw inspiration from?

**Comment by sosthene-nitrokey** [comment]
https://github.com/Nitrokey/opcard-rs/blob/main/examples/usbip.rs#L36

Enable the `ccid` feature of the `pc-usbip-runner` and it will work.

**Comment by szszszsz** [comment]
Ah, I thought this one does not work. Will check it on the next occasion.

**Comment by sosthene-nitrokey** [comment]
You might get the kernel bug, but we ever only reached it when using `pcscd` so you should be fine
