### ISSUE TITLE
Support longer secret for HMAC challenge-response

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/trussed-secrets-app#89]
Support longer secrets for HMAC challenge-response. Currently only 20 bytes secret length is allowed, whereas YK can support 40 bytes.

Edit: source:
- https://github.com/Nitrokey/nitrokey-3-firmware/issues/281#issuecomment-1580372655

**Comment by BayLee4** [comment]
It seems YK does not support 40 bytes secrets, only 20 bytes: https://developers.yubico.com/Developer_Program/Guides/User_Loaded_Data.html#_challenge_response

As the secret is encoded as hex, it is 40 characters long though. This is probably where the confusion comes from.

**Comment by szszszsz** [comment]
Good spot @BayLee4!

@orolhawion Can you confirm that in your use case?

**Comment by orolhawion** [comment]
sorry for the wait. the answer is: yes, I can confirm that it is a 40 character hex string, so @BayLee4 is right. thanks for the headsup.

**Comment by szszszsz** [comment]
Thank you for checking @orolhawion !
I am sorry, but we do not plan to extend this feature. It was added only to support existing solutions/workflows.
Closing as won't fix/no changes.

**Comment by orolhawion** [comment]
Too bad, I cannot import my secret to NK3 then. I tried to create an ASCII-String from the Hex-String but no result is accepted by NK3 Secrets app:

> $ nitropy nk3 secrets add-challenge-response 1 mySecretWithNonAsciiCharacters
Command line tool to interact with Nitrokey devices 0.4.39
Critical error:
An unhandled exception occurred
	Exception encountered: ValueError('string argument should contain only ASCII characters')

I used the following Kotlin code to create the 20 byte string:

```
@Test fun canDecode() {
      val hex = "4578616d706C6521"
      val chars = hex.chunked(2)
          .map { it.toInt(16).toByte() }
          .toByteArray()
          .toString(Charsets.UTF_8)

      print(chars) // prints Example!
  }
```

I tried other charsets but the error remains.

**Comment by szszszsz** [comment]
@orolhawion The secret argument should be encoded in base32, so you need to convert that binary into that encoding.
E.g. use `echo -e secret | base32`

**Comment by orolhawion** [comment]
Hi, 

encoding the secret to base32 results in a string with a length of 30 bytes. `nitropy` denies that stating it has to be exactly 20 bytes. 

I did the following: `base -d -i <fileWithMybase64EncodedSecret> | base32`

**Comment by Ingo-Albrecht** [comment]
@orolhawion I browse this issue just now. You can convert the YK hex secret with xxd before piping it to base32. See https://support.nitrokey.com/t/setup-otp-challenge-response-for-keepassxc/5497/1 for the procedure.

**Comment by orolhawion** [comment]
That worked. Thanks for the hint.
